/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/IGdyWwa73Ek
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/

import { Input } from "@/Components/ui/input";
import { Button } from "@/Components/ui/button";
import { Link } from "@nextui-org/react";

export function Footer({ isFixed = false }) {
    const footerClass = isFixed
        ? "fixed bottom-0 w-full"
        : "sticky bottom-0 w-full";
    return (
        <footer
            className={`${footerClass} bg-gray-100 dark:bg-gray-800  lg:py-20`}
        >
            <div className="container mx-auto px-4 md:px-6 grid grid-cols-4 md:grid-cols-2 lg:grid-cols-4 gap-8">
                <div className="flex flex-col gap-4">
                    <Link className="flex items-center gap-2" href="#">
                        <MountainIcon className="h-6 w-6 text-gray-900 dark:text-gray-50" />
                        <span className="text-lg font-semibold text-gray-900 dark:text-gray-50">
                            Acme Inc
                        </span>
                    </Link>
                    <p className="text-gray-500 dark:text-gray-400">
                        Acme Inc is a leading provider of innovative solutions
                        for businesses of all sizes.
                    </p>
                </div>
                <div className="flex flex-col gap-4">
                    <h4 className="text-lg font-semibold text-gray-900 dark:text-gray-50">
                        Quick Links
                    </h4>
                    <nav className="flex flex-col gap-2">
                        <Link
                            className="text-gray-500 hover:text-gray-900 dark:text-gray-400 dark:hover:text-gray-50"
                            href="#"
                        >
                            Home
                        </Link>
                        <Link
                            className="text-gray-500 hover:text-gray-900 dark:text-gray-400 dark:hover:text-gray-50"
                            href="#"
                        >
                            About
                        </Link>
                        <Link
                            className="text-gray-500 hover:text-gray-900 dark:text-gray-400 dark:hover:text-gray-50"
                            href="#"
                        >
                            Services
                        </Link>
                        <Link
                            className="text-gray-500 hover:text-gray-900 dark:text-gray-400 dark:hover:text-gray-50"
                            href="#"
                        >
                            Contact
                        </Link>
                    </nav>
                </div>
                <div className="flex flex-col gap-4">
                    <h4 className="text-lg font-semibold text-gray-900 dark:text-gray-50">
                        Resources
                    </h4>
                    <nav className="flex flex-col gap-2">
                        <Link
                            className="text-gray-500 hover:text-gray-900 dark:text-gray-400 dark:hover:text-gray-50"
                            href="#"
                        >
                            Blog
                        </Link>
                        <Link
                            className="text-gray-500 hover:text-gray-900 dark:text-gray-400 dark:hover:text-gray-50"
                            href="#"
                        >
                            Documentation
                        </Link>
                        <Link
                            className="text-gray-500 hover:text-gray-900 dark:text-gray-400 dark:hover:text-gray-50"
                            href="#"
                        >
                            Tutorials
                        </Link>
                        <Link
                            className="text-gray-500 hover:text-gray-900 dark:text-gray-400 dark:hover:text-gray-50"
                            href="#"
                        >
                            FAQs
                        </Link>
                    </nav>
                </div>
                <div className="flex flex-col gap-4">
                    <h4 className="text-lg font-semibold text-gray-900 dark:text-gray-50">
                        Newsletter
                    </h4>
                    <p className="text-gray-500 dark:text-gray-400">
                        Subscribe to our newsletter to stay up-to-date with our
                        latest news and updates.
                    </p>
                    <form className="flex gap-2">
                        <Input
                            className="flex-1"
                            placeholder="Enter your email"
                            type="email"
                        />
                        <Button type="submit">Subscribe</Button>
                    </form>
                </div>
            </div>
        </footer>
    );
}

function MountainIcon(props) {
    return (
        <svg
            {...props}
            xmlns="http://www.w3.org/2000/svg"
            width="24"
            height="24"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            strokeWidth="2"
            strokeLinecap="round"
            strokeLinejoin="round"
        >
            <path d="m8 3 4 8 5-5 5 15H2L8 3z" />
        </svg>
    );
}
